name: CI
on: [push, pull_request]
jobs:
  specs:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos ]
        ruby: [ 2.3, 2.4, 2.5 ]
        repeat: [ 1, 2, 3, 4, 5 ]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - run: brew install automake
      if: matrix.os == 'macos'

    # Bundler 2 seems to fix installing rubygems-tasks on Ruby < 2.4
    - run: gem install bundler --no-document
    - run: bundle env
    - run: bundle install --verbose
